# Generated by Django 6.0.3 on 2026-03-12 06:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('special_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cloud-image')),
                ('special_thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cloud-thumbnail')),
            ],
        ),
    ]
